#include <platform/GDriveAuthManager.hpp>

#include <cstdio>
#include <cstdint>
#include <ctime>
#include <fstream>
#include <iterator>
#include <mutex>
#include <string>
#include <vector>

#include <curl/curl.h>

#include <platform/CurlRuntime.hpp>
#include <third_party/nlohmann/json.hpp>

namespace shield::platform {
namespace {

using Json = nlohmann::json;

constexpr const char *kSdCredentialsPath = "sdmc:/switch/LiteFoil/credentials.json";
constexpr const char *kSdTokenPath = "sdmc:/switch/LiteFoil/gdrive.token";
constexpr const char *kFallbackCredentialsPath = "credentials.json";
constexpr const char *kFallbackTokenPath = "gdrive.token";
constexpr const char *kDefaultTokenUri = "https://oauth2.googleapis.com/token";
constexpr std::int64_t kRefreshSafetyWindowSeconds = 300;

struct OAuthClientConfig {
    std::string client_id;
    std::string client_secret;
    std::string token_uri = kDefaultTokenUri;
};

struct OAuthTokenState {
    std::string access_token;
    std::string refresh_token;
    std::string expiry;
    std::string path;
    Json original_json = Json::object();
};

std::mutex &AuthMutex() {
    static std::mutex mutex;
    return mutex;
}

bool ReadTextFile(const char *path, std::string &out) {
    std::ifstream stream(path, std::ios::binary);
    if(!stream.good()) {
        return false;
    }

    out.assign(std::istreambuf_iterator<char>(stream), std::istreambuf_iterator<char>());
    return true;
}

bool WriteTextFileAtomic(const std::string &path, const std::string &content) {
    if(path.empty()) {
        return false;
    }

    const std::string tmp_path = path + ".tmp";
    {
        std::ofstream stream(tmp_path, std::ios::binary | std::ios::trunc);
        if(!stream.good()) {
            return false;
        }
        stream.write(content.data(), static_cast<std::streamsize>(content.size()));
        if(!stream.good()) {
            return false;
        }
    }

    std::remove(path.c_str());
    return std::rename(tmp_path.c_str(), path.c_str()) == 0;
}

std::string JsonString(const Json &json, const char *key) {
    const auto it = json.find(key);
    if((it != json.end()) && it->is_string()) {
        return it->get<std::string>();
    }
    return {};
}

std::int64_t JsonInt64(const Json &json, const char *key, std::int64_t fallback = 0) {
    const auto it = json.find(key);
    if(it == json.end()) {
        return fallback;
    }
    if(it->is_number_integer()) {
        return it->get<std::int64_t>();
    }
    if(it->is_number_unsigned()) {
        return static_cast<std::int64_t>(it->get<std::uint64_t>());
    }
    if(it->is_string()) {
        const std::string raw = it->get<std::string>();
        if(raw.empty()) {
            return fallback;
        }
        std::int64_t sign = 1;
        std::size_t index = 0;
        if(raw[index] == '-') {
            sign = -1;
            ++index;
        }
        std::int64_t value = 0;
        for(; index < raw.size(); ++index) {
            const char c = raw[index];
            if(c < '0' || c > '9') {
                return fallback;
            }
            value = (value * 10) + (c - '0');
        }
        return value * sign;
    }
    return fallback;
}

bool ParseFixedInt(const std::string &value, std::size_t offset, std::size_t count, int &out) {
    if(offset + count > value.size()) {
        return false;
    }

    int result = 0;
    for(std::size_t i = 0; i < count; ++i) {
        const char c = value[offset + i];
        if(c < '0' || c > '9') {
            return false;
        }
        result = (result * 10) + (c - '0');
    }
    out = result;
    return true;
}

// Howard Hinnant's civil-date conversion.  This avoids relying on timegm(),
// which is not consistently available across the Windows/devkitPro toolchain.
std::int64_t DaysFromCivil(int year, unsigned month, unsigned day) {
    year -= month <= 2;
    const int era = (year >= 0 ? year : year - 399) / 400;
    const unsigned yoe = static_cast<unsigned>(year - era * 400);
    const unsigned doy = (153 * (month + (month > 2 ? -3 : 9)) + 2) / 5 + day - 1;
    const unsigned doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    return era * 146097 + static_cast<int>(doe) - 719468;
}

bool ParseIsoUtc(const std::string &value, std::int64_t &out_epoch_seconds) {
    // Accept the token shape generated by common OAuth helpers:
    // 2026-04-12T23:57:02Z (fractional seconds are ignored if present).
    if(value.size() < 19 || value[4] != '-' || value[7] != '-' ||
       (value[10] != 'T' && value[10] != ' ') || value[13] != ':' || value[16] != ':') {
        return false;
    }

    int year = 0, month = 0, day = 0, hour = 0, minute = 0, second = 0;
    if(!ParseFixedInt(value, 0, 4, year) ||
       !ParseFixedInt(value, 5, 2, month) ||
       !ParseFixedInt(value, 8, 2, day) ||
       !ParseFixedInt(value, 11, 2, hour) ||
       !ParseFixedInt(value, 14, 2, minute) ||
       !ParseFixedInt(value, 17, 2, second)) {
        return false;
    }

    if(month < 1 || month > 12 || day < 1 || day > 31 ||
       hour < 0 || hour > 23 || minute < 0 || minute > 59 || second < 0 || second > 60) {
        return false;
    }

    out_epoch_seconds = DaysFromCivil(year, static_cast<unsigned>(month), static_cast<unsigned>(day)) * 86400
        + hour * 3600 + minute * 60 + second;
    return true;
}

std::string FormatIsoUtc(std::time_t timestamp) {
    std::tm *utc = std::gmtime(&timestamp);
    if(utc == nullptr) {
        return {};
    }

    char buffer[96] = {};
    std::snprintf(buffer, sizeof(buffer), "%04d-%02d-%02dT%02d:%02d:%02dZ",
        utc->tm_year + 1900,
        utc->tm_mon + 1,
        utc->tm_mday,
        utc->tm_hour,
        utc->tm_min,
        utc->tm_sec);
    return buffer;
}

bool HasFreshAccessToken(const OAuthTokenState &token) {
    if(token.access_token.empty() || token.expiry.empty()) {
        return false;
    }

    std::int64_t expiry_epoch = 0;
    if(!ParseIsoUtc(token.expiry, expiry_epoch)) {
        return false;
    }

    const auto now = static_cast<std::int64_t>(std::time(nullptr));
    return expiry_epoch > now + kRefreshSafetyWindowSeconds;
}

bool LoadClientConfig(OAuthClientConfig &config) {
    std::string raw;
    if(!ReadTextFile(kSdCredentialsPath, raw) && !ReadTextFile(kFallbackCredentialsPath, raw)) {
        return false;
    }

    const Json root = Json::parse(raw, nullptr, false);
    if(root.is_discarded() || !root.is_object()) {
        return false;
    }

    const Json *client = &root;
    const auto installed = root.find("installed");
    const auto web = root.find("web");
    if((installed != root.end()) && installed->is_object()) {
        client = &(*installed);
    }
    else if((web != root.end()) && web->is_object()) {
        client = &(*web);
    }

    config.client_id = JsonString(*client, "client_id");
    config.client_secret = JsonString(*client, "client_secret");
    const std::string token_uri = JsonString(*client, "token_uri");
    if(!token_uri.empty()) {
        config.token_uri = token_uri;
    }

    return !config.client_id.empty() && !config.client_secret.empty();
}

bool LoadTokenState(OAuthTokenState &token) {
    std::string raw;
    if(ReadTextFile(kSdTokenPath, raw)) {
        token.path = kSdTokenPath;
    }
    else if(ReadTextFile(kFallbackTokenPath, raw)) {
        token.path = kFallbackTokenPath;
    }
    else {
        return false;
    }

    const Json root = Json::parse(raw, nullptr, false);
    if(root.is_discarded() || !root.is_object()) {
        return false;
    }

    token.original_json = root;
    token.access_token = JsonString(root, "access_token");
    token.refresh_token = JsonString(root, "refresh_token");
    token.expiry = JsonString(root, "expiry");
    if(token.expiry.empty()) {
        token.expiry = JsonString(root, "expires_at");
    }
    return !token.refresh_token.empty();
}

std::string EscapeFormValue(CURL *curl, const std::string &value) {
    char *escaped = curl_easy_escape(curl, value.c_str(), static_cast<int>(value.size()));
    if(escaped == nullptr) {
        return {};
    }
    std::string result(escaped);
    curl_free(escaped);
    return result;
}

std::string BuildRefreshBody(CURL *curl, const OAuthClientConfig &config, const OAuthTokenState &token) {
    return "client_id=" + EscapeFormValue(curl, config.client_id)
        + "&client_secret=" + EscapeFormValue(curl, config.client_secret)
        + "&refresh_token=" + EscapeFormValue(curl, token.refresh_token)
        + "&grant_type=refresh_token";
}

std::size_t WriteStringCallback(char *ptr, std::size_t size, std::size_t nmemb, void *userdata) {
    auto *out = static_cast<std::string *>(userdata);
    const std::size_t bytes = size * nmemb;
    if(out != nullptr) {
        out->append(ptr, bytes);
    }
    return bytes;
}

bool RefreshAccessToken(const OAuthClientConfig &config, OAuthTokenState &token, std::string &error) {
    CURL *curl = AcquireThreadCurlHandle();
    if(curl == nullptr) {
        error = "curl init failed";
        return false;
    }

    std::string response;
    const std::string body = BuildRefreshBody(curl, config, token);
    if(body.empty()) {
        error = "failed to encode oauth request";
        return false;
    }

    struct curl_slist *headers = nullptr;
    headers = curl_slist_append(headers, "Content-Type: application/x-www-form-urlencoded");
    headers = curl_slist_append(headers, "Accept: application/json");

    curl_easy_setopt(curl, CURLOPT_URL, config.token_uri.c_str());
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 3L);
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
    curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L);
    curl_easy_setopt(curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
    curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, static_cast<long>(CURL_HTTP_VERSION_1_1));
    curl_easy_setopt(curl, CURLOPT_USERAGENT, "LiteFoil/2.0");
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
    curl_easy_setopt(curl, CURLOPT_POST, 1L);
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, body.c_str());
    curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, static_cast<long>(body.size()));
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteStringCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
    curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT_MS, 15000L);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, 30000L);

    const CURLcode rc = curl_easy_perform(curl);
    long http_code = 0;
    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);

    if(headers != nullptr) {
        curl_slist_free_all(headers);
    }

    if((rc != CURLE_OK) || (http_code < 200) || (http_code >= 300)) {
        error = (rc != CURLE_OK) ? curl_easy_strerror(rc) : ("HTTP " + std::to_string(http_code));
        return false;
    }

    const Json root = Json::parse(response, nullptr, false);
    if(root.is_discarded() || !root.is_object()) {
        error = "invalid oauth response";
        return false;
    }

    const std::string access_token = JsonString(root, "access_token");
    if(access_token.empty()) {
        error = "oauth response missing access_token";
        return false;
    }

    token.access_token = access_token;
    const std::int64_t expires_in = JsonInt64(root, "expires_in", 3600);
    if(expires_in > 0) {
        const auto refreshed_expiry = std::time(nullptr) + static_cast<std::time_t>(expires_in);
        token.expiry = FormatIsoUtc(refreshed_expiry);
    }

    Json saved = token.original_json.is_object() ? token.original_json : Json::object();
    saved["access_token"] = token.access_token;
    saved["refresh_token"] = token.refresh_token;
    if(!token.expiry.empty()) {
        saved["expiry"] = token.expiry;
    }

    // Prefer updating the file that was loaded.  If the developer fallback was
    // used, keep the write local instead of creating a surprise SD credential.
    if(!WriteTextFileAtomic(token.path, saved.dump(4) + "\n")) {
        // A refreshed in-memory token is still usable for this session.
        error.clear();
    }

    return true;
}

GDriveAuthorization BuildAuthorization(bool force_refresh) {
    OAuthClientConfig config;
    OAuthTokenState token;
    if(!LoadTokenState(token)) {
        return { false, {}, "gdrive.token not found" };
    }

    if(!force_refresh && HasFreshAccessToken(token)) {
        return { true, token.access_token, {} };
    }

    if(!LoadClientConfig(config)) {
        return { false, {}, "credentials.json not found or invalid" };
    }

    std::string error;
    if(!RefreshAccessToken(config, token, error)) {
        return { false, {}, error.empty() ? "oauth refresh failed" : error };
    }

    return { true, token.access_token, {} };
}

}

GDriveAuthorization GDriveAuthManager::GetAuthorization(bool force_refresh) {
    std::lock_guard<std::mutex> lock(AuthMutex());
    return BuildAuthorization(force_refresh);
}

}
